[tool]
[tool.poetry]
authors = ["Binaghi Pablo Martin <martin.binaghi01@gmail.com>"]
description = ""
name = "root"
version = "0.0.0"
[tool.poetry.dependencies]
pandas = "*"
python = "^3.8"
scipy = "*"
